version: '2'
services:
  prueba-app:
    image: prueba
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://prueba-mysql:3306/prueba?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://prueba-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://prueba-elasticsearch:9200
    ports:
      - 8080:8080
  prueba-mysql:
    extends:
      file: mysql.yml
      service: prueba-mysql
  prueba-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: prueba-elasticsearch
